<?= $this->w1; ?>
<table style="margin-left: auto;margin-right: auto">
    
    <?php
        
    if(count($this->items)>0)
        foreach($this->items as $item)
        {
            if ($item instanceof App_ItemDTO)
            {
                //echo "<tr> <td>$item->id</td> <td>$item->user</td> <td>$item->email</td> <td>$item->date</td> <td>$item->message</td></tr>";
                ///item/edit/$item->id
                echo "<table style='margin-left: auto;margin-right: auto; border-style: double'><tr><td>";
                echo "<tr><th>$item->date</th><td width='500px'><a href='" . $this->url(array('controller'=>'item','action'=>'edit','id'=>$item->id)) . "'>edit</a>"
                        . " / <a href='" . $this->url(array('controller'=>'item','action'=>'delete','id'=>$item->id)) . "'>delete</a></td></tr>";
                echo "<tr><th></th><td width='500px'>$item->message</td></tr>";
                echo "<tr><th></th><td style='float: right'>";
                if ($item->email!='no@email.com')
                    echo "<a href='mailto:$item->email'>$item->user</a></td></tr>";
                else
                    echo "$item->user</td></tr>";
                echo "</td></tr></table>";
            }
        }
    else
    {
        echo "<tr><td>Brak wiadomości.</td></tr>";
    }
    ?>
</table>